# Change these first
owner: qwq233 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://qwq2333.top
  - name: Bitwarden
    url: https://pass.qwq2333.top
  - name: AuthServer
    method: POST
    url: https://api.qwq2333.top/qa/user/query
    headers:
      - "Content-Type: application/json"
    body: '{ "uin": 731555702 }'
  - name: NextCloud
    url: https://cloud.qwq2333.top
  - name: Jenkins
    url: https://apk.qwq2333.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.qwq2333.top
  logoUrl: https://qwq2333.top/wp-content/uploads/2022/03/avatar-new.png
  name: Status Pages
  introTitle: "James Clef's Site Statuspage"
  introMessage: Hope these things will not die
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/qwq233
    - title: My Blog
      href: https://qwq2333.top/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
